### ISSUE TITLE
Train using paragraphs of Story and then predict future?

### ISSUE THREAD

**Issue by krigeta** [e-tony/Story_Generator_RnM#1]
Hello thanks for this awesome repo, I am wondering if it is possible to predict future events based on the past events of a story?

like instead of input the whole conversation using characters, we can able to input the whole story and then able to predict the future?

**Comment by e-tornike** [comment]
Hey @krigeta,

thanks for your interest! 

If I understand it correctly, you want to predict text (i.e., output) that follows from previous text (i.e., input)? If so, then I would recommend looking at Language Modeling (e.g., [BERT](https://www.aclweb.org/anthology/N19-1423/) or [GPT-2](https://www.semanticscholar.org/paper/Language-Models-are-Unsupervised-Multitask-Learners-Radford-Wu/9405cc0d6169988371b2755e573cc28650d14dfe)). [This blog](https://lena-voita.github.io/nlp_course/language_modeling.html) explains it very well.

Hope that helps. Cheers!

**Comment by krigeta** [comment]
Hey, Actually I am using the GPT-Neo an alternative of GPT-3 and it generates text but the output is not that good. So thinking to finetune the GPT-2 using your collab but the dataset i have is in paragraphs not like in dialogue format.

So i was asking you that how can I use the dataset I have to finetune the GPT-2 using your colab?

**Comment by e-tornike** [comment]
I see. I would take a look at the most recent examples by HuggingFace (see language-modeling or the Colab notebook listed [here](https://github.com/huggingface/transformers/tree/master/examples/pytorch)) and you can definitely ask questions and find answers in the issues there.

**Comment by krigeta** [comment]
okay will do that and please let me know if you find something related. that would be a great help.
